@file:Suppress("MaxLineLength") // 64-byte hex test vectors are inherently longer than a line

package org.offlinemesh.app.gateway

import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/** Vectors 0 and 1 are the official BIP-340 vectors; the other six were generated by libsecp256k1
 *  (via coincurve) so this signer is checked against an independent implementation. */
class Bip340Test {

    private class Vector(val sk: String, val pk: String, val aux: String, val msg: String, val sig: String)

    private val vectors = listOf(
        Vector("0000000000000000000000000000000000000000000000000000000000000003",
            "f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9",
            "0000000000000000000000000000000000000000000000000000000000000000",
            "0000000000000000000000000000000000000000000000000000000000000000",
            "e907831f80848d1069a5371b402410364bdf1c5f8307b0084c55f1ce2dca821525f66a4a85ea8b71e482a74f382d2ce5ebeee8fdb2172f477df4900d310536c0"),
        Vector("b7e151628aed2a6abf7158809cf4f3c762e7160f38b4da56a784d9045190cfef",
            "dff1d77f2a671c5f36183726db2341be58feae1da2deced843240f7b502ba659",
            "0000000000000000000000000000000000000000000000000000000000000001",
            "243f6a8885a308d313198a2e03707344a4093822299f31d0082efa98ec4e6c89",
            "6896bd60eeae296db48a229ff71dfe071bde413e6d43f917dc8dcf8c78de33418906d11ac976abccb20b091292bff4ea897efcb639ea871cfa95f6de339e4b0a"),
        Vector("624678570e033e539584b079021c743e3d1c383e3efae4e148fcb6fa6f957a82",
            "9523669753317f210ad623d6ec4eb7bb7ce4c8d193314e29c329fa3f17e0b46b",
            "a28b136c626b900d6e2ed5a13fe672bf8692b34dbb4043394382210204b1c1b2",
            "2ce6150f3416e2ccae2928047e753d78fdb8fcb4fe861412129a9e8e3042ab97",
            "4e0e5125c2168d1cc766e8ace445ff6fc359820bcb82160797f6d3fbe9d5483cd75eeeb96078659d8df75e740ce1c5efbbead63c058ae96beeddb531bd862ff0"),
        Vector("8adf736b9c693d16babb6f70a0a6618e09ed6c84febc336b2e4f9a614c907fe1",
            "443f86aca01d31e5e4265304988679b1ea76e3fa7c341c355f0e5932ad9d0f45",
            "291cf9c531911aad146aa04094c33d340aa9249d1fd4073eae25d9d85acbac96",
            "1cb08a745afffecbcbf036f4e172933acdd87ec67e1f96a10d6bc36cf7cba794",
            "782b40aad00b12e6541fdfb5efd0c32aae46017417c3a53185208c3803034c8900c51058b5ac2905014144f7b2c93233e66796ec06cbcd3d3f2639ed8bc270b1"),
        Vector("f3aaf378857f3047dfe5cd8f34392dc954d54aa5fc1eefb2a98850974742513d",
            "e29bf33f4a2bdd9fcd1f6e485c19b61f7901d8072f7dfe17dfec6717b950d39c",
            "6bbfb42b4181e32b5a2323376d502bf62f5c41ea92c3e8221919393b9117e943",
            "325d1a24aab59a22ad22f6d4c3ba4c38fad7494becbae563e6866db631c5c628",
            "f6c4891b360ebed7367679accb289e7be543849c3eb99ce964f98030f99726cfc1a4b8be3979375e60513fba5a142f532f970a90a5aa0cd63be501d3491a825d"),
        Vector("45d5c844bcb9a1547182c416dad5c1d44089b5fd45c5e105c02e233719f1944e",
            "3f1ebbf6ab08b31637044fa20ceea18d988fe5a002bad494fee1590cae3e2149",
            "20fff6465535249cb51975854f7e0713dd24d397cf94ef1d9587d7656a2141ae",
            "27e737a0bd88a565d14969b3eaebfbebbf0cab7d1c40437fc317c3e88d864f91",
            "4eaa8bc0cfbbd8fa7a2817bf6a73f903ed1cb3e3fe3c080ef1e635c1bee88d79c0b71699e79bde6921473c8a8c5a0cdd11edc4233bb11e34f020074d94d471cf"),
        Vector("df7a38fe32aa433059ec703f9d3ba73d2bcd7eed0f6cce755aff5fac65d54606",
            "c25b4ce2ef99e3da58e7a725a496fee3015da94ee6dc8c3494b28d4e1a04ab50",
            "acc960b67a9f8781b403c21ae65a5f24559b28efca25aed0c87a1a1ae4c9ce2e",
            "1b171b4bdab1a708779bfec81e5aa5e9fe14d7a0bd497d9b1711e8a2d563ca45",
            "b91c967c59dd9b3b92b6166d87cc748209d1002bafc79548b88d5674498893469ea78720b86ddec567758607c9e051d684f4ff2c548879dddc89a5a7450bc5ea"),
        Vector("264e3d5c91a53a81b411fbb6e019df0e96d8d6988cfff4b9ef31cf43e940ae68",
            "573ee28f0e0ee73a314e2ec012ac3e677e7bf76c194f8afd56dffb9c78bc1be7",
            "e6d6f095988329984b3557369b10bc1fb06791e6b744f1399cfbb2d2606a381a",
            "cd6e5fd19898e6c7de140091eb78e5f5e5eb9f2546ffc398c86fdf45221dcaeb",
            "0176b6ed45e8f347ce1ebcf876c152003a435fb31405a5e7780eb1fc87bf20bb41c0a927a907d8b8efc2007a68d7e48e95b116de6b3c3b0b4f4faaedd059eeb9"),
    )

    private fun hex(s: String) = ByteArray(s.length / 2) { s.substring(it * 2, it * 2 + 2).toInt(16).toByte() }
    private fun ByteArray.hex() = joinToString("") { "%02x".format(it) }

    @Test fun `signatures are byte-identical to the reference implementation`() {
        for (v in vectors) {
            val sig = Bip340.sign(hex(v.msg), hex(v.sk), hex(v.aux))
            assertTrue("vector ${v.sk.take(8)}", v.sig == sig.hex())
        }
    }

    @Test fun `reference signatures verify`() {
        for (v in vectors) assertTrue(Bip340.verify(hex(v.msg), hex(v.pk), hex(v.sig)))
    }

    @Test fun `derived public key equals the reference public key`() {
        for (v in vectors) assertTrue(v.pk == Bip340.publicKey(hex(v.sk)).hex())
    }

    @Test fun `a tampered message, signature or key fails verification`() {
        val v = vectors[1]
        val msg = hex(v.msg); val pk = hex(v.pk); val sig = hex(v.sig)
        assertFalse(Bip340.verify(msg.copyOf().also { it[0] = (it[0] + 1).toByte() }, pk, sig))
        assertFalse(Bip340.verify(msg, pk, sig.copyOf().also { it[10] = (it[10] + 1).toByte() }))
        assertFalse(Bip340.verify(msg, hex(vectors[0].pk), sig))
    }

    @Test fun `malformed sizes and out-of-range values are rejected not thrown`() {
        val v = vectors[0]
        assertFalse(Bip340.verify(ByteArray(31), hex(v.pk), hex(v.sig)))
        assertFalse(Bip340.verify(hex(v.msg), ByteArray(31), hex(v.sig)))
        assertFalse(Bip340.verify(hex(v.msg), hex(v.pk), ByteArray(63)))
        assertFalse(Bip340.verify(hex(v.msg), ByteArray(32) { 0xFF.toByte() }, hex(v.sig)))
        assertTrue(runCatching { Bip340.publicKey(ByteArray(32)) }.isFailure)
        assertTrue(runCatching { Bip340.publicKey(ByteArray(32) { 0xFF.toByte() }) }.isFailure)
    }

    @Test fun `different aux randomness gives a different but valid signature`() {
        val v = vectors[2]
        val a = Bip340.sign(hex(v.msg), hex(v.sk), ByteArray(32))
        val b = Bip340.sign(hex(v.msg), hex(v.sk), ByteArray(32) { 9 })
        assertFalse(a.contentEquals(b))
        assertTrue(Bip340.verify(hex(v.msg), hex(v.pk), a) && Bip340.verify(hex(v.msg), hex(v.pk), b))
    }
}
