package org.offlinemesh.app.gateway

import java.math.BigInteger
import java.security.MessageDigest

/**
 * BIP-340 Schnorr signatures over secp256k1, the signature scheme Nostr requires, in plain
 * `BigInteger` Kotlin so v3 adds no native crypto dependency (`PLAN-v2.md` §13.5).
 *
 * Checked against the official BIP-340 vectors 0 and 1 and six more vectors generated by
 * libsecp256k1 (`Bip340Test`), so this is not validated against itself. Affine arithmetic with one
 * modular inverse per step: roughly tens of milliseconds per signature on a phone, fine at the
 * gateway's one-event-per-second ceiling.
 *
 * **Not constant-time**, which is acceptable here only because the key it signs with is a throwaway
 * gateway key replaced every 7 days and protects no group content (decision 68). Do not reuse this for
 * a long-lived identity key.
 */
// TooManyFunctions: the curve arithmetic (add/mul/liftX) and the three hash/byte helpers are each one
// line of the BIP-340 reference algorithm; splitting them across files would hide that correspondence.
@Suppress("TooManyFunctions")
object Bip340 {
    private const val KEY_BYTES = 32
    private const val SIG_BYTES = 64
    private const val HEX_RADIX = 16
    private const val POSITIVE = 1

    private val P = BigInteger("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F", HEX_RADIX)
    private val N = BigInteger("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141", HEX_RADIX)
    private val G = Point(
        BigInteger("79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798", HEX_RADIX),
        BigInteger("483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8", HEX_RADIX),
    )
    private const val CONST_TWO = 2L
    private const val CONST_THREE = 3L
    private const val CURVE_B = 7L
    private const val SQRT_DIVISOR = 4L
    private val TWO = BigInteger.valueOf(CONST_TWO)
    private val THREE = BigInteger.valueOf(CONST_THREE)
    private val SEVEN = BigInteger.valueOf(CURVE_B)
    private val FOUR = BigInteger.valueOf(SQRT_DIVISOR)

    private class Point(val x: BigInteger, val y: BigInteger)

    /** x-only public key (32 bytes) for a 32-byte secret key. Throws if the key is out of range. */
    fun publicKey(secretKey: ByteArray): ByteArray {
        val d = scalar(secretKey)
        return bytes32(mul(d, G)!!.x)
    }

    /** Signs a 32-byte message with 32 bytes of auxiliary randomness. Returns 64 bytes. */
    fun sign(message: ByteArray, secretKey: ByteArray, aux: ByteArray): ByteArray {
        require(message.size == KEY_BYTES && aux.size == KEY_BYTES) { "message and aux must be 32 bytes" }
        val dPrime = scalar(secretKey)
        val pub = mul(dPrime, G)!!
        val d = if (isOdd(pub.y)) N.subtract(dPrime) else dPrime
        val pubBytes = bytes32(pub.x)
        val t = xor(bytes32(d), taggedHash("BIP0340/aux", aux))
        val kPrime = BigInteger(POSITIVE, taggedHash("BIP0340/nonce", t, pubBytes, message)).mod(N)
        check(kPrime.signum() != 0) { "nonce was zero" }
        val r = mul(kPrime, G)!!
        val k = if (isOdd(r.y)) N.subtract(kPrime) else kPrime
        val rBytes = bytes32(r.x)
        val e = BigInteger(POSITIVE, taggedHash("BIP0340/challenge", rBytes, pubBytes, message)).mod(N)
        return rBytes + bytes32(k.add(e.multiply(d)).mod(N))
    }

    fun verify(message: ByteArray, publicKey: ByteArray, signature: ByteArray): Boolean {
        val sizesOk = message.size == KEY_BYTES && publicKey.size == KEY_BYTES && signature.size == SIG_BYTES
        return sizesOk && verifySized(message, publicKey, signature)
    }

    private fun verifySized(message: ByteArray, publicKey: ByteArray, signature: ByteArray): Boolean {
        val pub = liftX(BigInteger(POSITIVE, publicKey))
        val rBytes = signature.copyOfRange(0, KEY_BYTES)
        val r = BigInteger(POSITIVE, rBytes)
        val s = BigInteger(POSITIVE, signature.copyOfRange(KEY_BYTES, SIG_BYTES))
        return if (pub == null || r >= P || s >= N) false else equationHolds(pub, r, s, publicKey, message)
    }

    private fun equationHolds(
        pub: Point,
        r: BigInteger,
        s: BigInteger,
        publicKey: ByteArray,
        message: ByteArray,
    ): Boolean {
        val e = BigInteger(POSITIVE, taggedHash("BIP0340/challenge", bytes32(r), publicKey, message)).mod(N)
        val point = add(mul(s, G), mul(N.subtract(e), pub))
        return point != null && !isOdd(point.y) && point.x == r
    }

    private fun scalar(secretKey: ByteArray): BigInteger {
        require(secretKey.size == KEY_BYTES) { "secret key must be 32 bytes" }
        val d = BigInteger(POSITIVE, secretKey)
        require(d.signum() > 0 && d < N) { "secret key out of range" }
        return d
    }

    private fun liftX(x: BigInteger): Point? {
        if (x >= P) return null
        val ySquared = x.multiply(x).multiply(x).add(SEVEN).mod(P)
        val y = ySquared.modPow(P.add(BigInteger.ONE).divide(FOUR), P)
        if (y.modPow(TWO, P) != ySquared) return null
        return Point(x, if (isOdd(y)) P.subtract(y) else y)
    }

    private fun add(a: Point?, b: Point?): Point? {
        if (a == null) return b
        if (b == null) return a
        if (a.x == b.x && a.y != b.y) return null
        val lambda = if (a.x == b.x) {
            THREE.multiply(a.x).multiply(a.x).multiply(TWO.multiply(a.y).modInverse(P)).mod(P)
        } else {
            b.y.subtract(a.y).multiply(b.x.subtract(a.x).mod(P).modInverse(P)).mod(P)
        }
        val x = lambda.multiply(lambda).subtract(a.x).subtract(b.x).mod(P)
        return Point(x, lambda.multiply(a.x.subtract(x)).subtract(a.y).mod(P))
    }

    private fun mul(k: BigInteger, point: Point): Point? {
        var result: Point? = null
        var addend: Point? = point
        for (i in 0 until k.bitLength()) {
            if (k.testBit(i)) result = add(result, addend)
            addend = add(addend, addend)
        }
        return result
    }

    private fun isOdd(v: BigInteger) = v.testBit(0)

    private fun bytes32(v: BigInteger): ByteArray {
        val raw = v.toByteArray()
        return when {
            raw.size == KEY_BYTES -> raw
            raw.size > KEY_BYTES -> raw.copyOfRange(raw.size - KEY_BYTES, raw.size)
            else -> ByteArray(KEY_BYTES - raw.size) + raw
        }
    }

    private fun xor(a: ByteArray, b: ByteArray) = ByteArray(a.size) { (a[it].toInt() xor b[it].toInt()).toByte() }

    private fun taggedHash(tag: String, vararg parts: ByteArray): ByteArray {
        val tagHash = MessageDigest.getInstance("SHA-256").digest(tag.toByteArray(Charsets.UTF_8))
        val md = MessageDigest.getInstance("SHA-256")
        md.update(tagHash); md.update(tagHash)
        for (p in parts) md.update(p)
        return md.digest()
    }
}
